version: '3.7'

services:
  redis:
    image: redis
    command: redis-server
    volumes:
    - ./deployment/redis:/data
    ports:
    - 6379:6379
    restart: always

  db:
    image: postgres:12.1
    volumes:
    - postgres_data:/var/lib/postgresql/data/


  web:
    build: .
    #image: django-project
    #command: python /code/manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - .:/ordering
      - /tmp/logs:/tmp
    command: bash start.sh
    links:
      - db
      - redis
#    ports:
#    - 8888:8000
    depends_on:
      - db
      - redis
    restart: always

  nginx:
    build: deployment/nginx
    ports:
    - 80:80
    - 443:443
    expose:
      - 8000
    volumes:
    - ./staticfiles:/usr/share/nginx/html/static
    - ./media:/usr/share/nginx/html/media
    - ./deployment/nginx/ssl:/usr/share/nginx/ssl
    links:
      - web
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
